### ISSUE TITLE
Совещание команды JClean

### ISSUE THREAD

**Issue by seanjke** [khasang/JClean#13]
Тема:
Обсуждение архитектуры и верстки.

**Comment by Mauladen** [comment]
Так же поднимаем вопрос про алгоритм поиска (надо уже выбрать куда копать)

**Comment by seanjke** [comment]
29.08.15 Состоялось совещание команды JClean.
Состав участников :
Иван Бердюгин (PM, Аrchitect, Developer)
Анатолий Бурдейный (UI designer, Developer)
Георгий Семенов (Usability designer, Developer)
Александр Любимов (PR, Developer)
Мамедалиев Ильгар (Usability designer, Developer)
Львов Дмитрий (Usability designer, PR, Developer)
Данил Антошкин (Product owner, Аrchitect, Developer)

Главным образом определились с глобальной моделью архитектуры. Приняли решение использовать популярный шаблон проектирования MVC.
Были разобраны диаграммы UML, на которых представлена общая концепция архитектуры приложения (https://github.com/khasang/JClean/blob/seanjke-architecture/uml/More%20details%20MVC%20Sequence%20Diagram.txt).
Была предложена идея реализации блока View, смысл которого в том, чтобы исключить прямую зависимость окон по отношению друг у другу средствами механизма коммуникаций между окнами и контроллером. Детально механизм будет представлен в виде диаграмм. Было принято решение не выполнять работы по разработке архитектуры одновременно с версткой. 

Было поставлено несколько задач для всей команды:
1. В течении недели разобраться с популярными реализациями шаблона MVC
2. Скачать с github пример реализации архитектуры, разобраться в нем, сформировать предложения по его улучшению.
3. Сформировать предложения по улучшению архитектуры. 
4. К концу недели, сформировать первую рабочую архитектуру проекта.
5. Утвердить архитектуру и перейти на следующий шаг.
