### ISSUE TITLE
Совещание команды JClean 05.09.15

### ISSUE THREAD

**Issue by seanjke** [khasang/JClean#14]
У нас на повестке согласование архитектуры, обсуждение некоторых деталей реализации и распределение будущих задач.

Обсудим порядок выполнения и вообще общие пожелания, кто какие задачи хотел бы делать

**Comment by seanjke** [comment]
Состав участников:

Иван Бердюгин (PM, Аrchitect, Developer)
Анатолий Бурдейный (UI designer, Developer)
Георгий Семенов (Usability designer, Developer)
Мамедалиев Ильгар (Usability designer, Developer)

На собрании была принята предложенная архитектура приложения. 
Обсудили пожелания участников относительно выбора направления деятельности, а именно:
1. Разработка интерфейсной части приложения.
 Иван Бердюгин (PM, Аrchitect, Developer)
 Анатолий Бурдейный (UI designer, Developer)
2. Разработка модели приложения.
 Георгий Семенов (Usability designer, Developer)
 Мамедалиев Ильгар (Usability designer, Developer)
В дальнейшем список расширится. 
Также обсудили некоторые детали относительно сложностей в реализации интерфейсной части. Основная проблема заключается в отсутствии готовых, бесплатных решений. Надо готовиться к тому, что все составляющие интерфейса придется выполнить самим.

**Comment by DemonStars** [comment]
двиньте карточку в trello на следующий степ!
