### ISSUE TITLE
Предпочтения по участкам разработки приложения

### ISSUE THREAD

**Issue by seanjke** [khasang/JClean#15]
Отпишитесь, кто какую часть приложения хотел бы реализовать.
1. Интерфейсная часть
2. Разработка модели
3. Разработка контроллеров

**Comment by Mauladen** [comment]
Разработка модели, могу ещё и мелкие задачи

**Comment by Fedorm** [comment]
1. Интерфейсная часть

**Comment by GamBitGit** [comment]
Модель

**Comment by GeorgeSemenov** [comment]
Модель.

**Comment by PStankevich** [comment]
Попытался бы с контроллерами (контроллером) :)
