### ISSUE TITLE
Создать первую страницу

### ISSUE THREAD

**Issue by gressus** [khasang/JClean#2]
![default](https://cloud.githubusercontent.com/assets/8287232/9285385/18c4de90-42ee-11e5-9b8d-7e58948555b4.png)

тестовая карточка

**Comment by gressus** [comment]
Не, такой дизайн никуда не годится! Нужно все вверх ногами сделать! И розовым!

**Comment by gressus** [comment]
Ну давайте попробуем

**Comment by TwerTrue** [comment]
Очень не удобный дизайн, и большие промужутки между сообщениями, Я думаю не надо это использовать

**Comment by gressus** [comment]
кроме промежутков между сообщениями больше пока никакой конкретики?

**Comment by TwerTrue** [comment]
Из за этого не удобно читать последовательное обжение, много пространства в некуда

**Comment by gressus** [comment]
Проверка скорости обновления

**Comment by gressus** [comment]
еще одна проверка

**Comment by gressus** [comment]
![default](https://cloud.githubusercontent.com/assets/8287232/9284199/5817a246-42e2-11e5-9707-4dbf95ced92e.png)
гипер крутая картинка дизайна

**Comment by gressus** [comment]
тест
