### ISSUE TITLE
Реализовать метод поиска дублей

### ISSUE THREAD

**Issue by seanjke** [khasang/JClean#21]
Реализация описана в карточке #5, автор @GamBitGit
Дополнением будет  то, что вместо класса Duplicate необходимо использовать класс JCFilePropertie. Так же необходимо учитывать, что метод должен возвращать HashMap<String, ArrayList<JCFilePropertie>> - где ключ это строковое представление хеш-суммы файла.

**Comment by GamBitGit** [comment]
А зачем ключом делать хеш-сумму? Лучше сразу при добавлении в список дубликатов, при совпадении размера, сверять хеш-суммы и в случае совпадения добавлять.Если же, после поиска всех дубликатов по размеру, начинать сравнивать их по хеш-сумме, дабы отсеять ненужные, то могут возникнуть проблемы, для решения которых прийдется усложнять алгоритм. Например в списке копий 6 файлов с одинаковым размером, при сравнении хеш-сумм оказалось, что 3 и 5 имеют отличные хеш-суммы от исходного файла, но они могут иметь одинаковые между собой, это прийдется проверять и в случае чего добавлять новый элемент в список. В случае со сравнением хеш-суммы на этапе добавления в список , этой проблемы можно избежать, и само значение можно не хранить.
Сейчас подумал, что размер файла ключом тоже нельзя оставлять=) не получится хранить файлы с одинаковым размером, но разным хешем. Хотя можно придумать какую-нибудь индексацию.

**Comment by GamBitGit** [comment]
Все правильно, чет я туплю=) будем хранить ключом хеш-сумму
