### ISSUE TITLE
Предложения по сравнению файлов 

### ISSUE THREAD

**Issue by Mauladen** [khasang/JClean#5]
Пишем какие есть идеи по сравнению файлов

**Comment by HepB** [comment]
Есть хеш-функция Adler-32 (https://ru.wikipedia.org/wiki/Adler-32), она реализована в библиотеках Java (значит, релазиуется просто). Минусами хеш-функции является возможность возникновения коллизий (одинаковых значений для разных данных). Однако, "вероятность фаер резиста крайне мала". Может быть реализовать возможность выбора пользователю, "быстрый" алгоритм, или "долгий".

**Comment by Mauladen** [comment]
Самый оптимальный вариант на данный момент который я нашёл

Вначале получаем полный список всех файлов и раскладываем их по размеру. Если размеры разные - файлы разные. Для них даже не считаем хэш. Если остались файлы с одинаковым размером, то считаем хеш для первого килобайта (мегабайта). Если он отличается - дальше нет смысла сравнивать. Если одинаковый - идем дальше, следующий мегабайт.

Так мы получим быстроту и качественную проверку

**Comment by seanjke** [comment]
В ходе многочисленных экспериментов, было установлено, что проверять части файлов с начала до конца - бессмысленно. Потому что если файлы отличаются только в самом конце, нам придется проверить весь файл целиком. А это и есть самое затратное место, которого мы пытаемся избежать. 

TwerTrue писал:
 -Если остались файлы с одинаковым размером, то считаем хеш для первого килобайта (мегабайта). Если он отличается - дальше нет смысла сравнивать. Если одинаковый - идем дальше, следующий мегабайт.

При таком подходе, нам постоянно надо будет перебирать коллекцию и сравнивать каждый дубль с каждым, а в купе с подсчетом сумм затраты по времени возрастают еще больше. 

Мой метод поиска дублей основан на двух типах коллекций :
1. HashMap
2. ArrayList.
Первый позволит нам, выявить дубли по размеру.  А второй позволит нам накапливать дубли. 
Логика такая:
Создаем HashMap<Long, File> где ключ карты - размер файла. Сканируем каталог и записываем в карту найденные фалы. Если карта возвращает не null, значит файл с там размером уже есть в коллекции, значит мы наткнулись на дубль. Помещаем в ArrayList найденный дубль и файл который уже был в карте(так как нам нужна полная картина, со всеми дублями).  Дальше перебираем ArrayList, считаем хэшсуммы дублей по оптимальному алгоритму(который еще надо будет разработать). Далее для того, чтобы выявить "настоящие" дубли, повторяем тот же алгоритм. Только теперь ключом карты будет хэшсумма.  
Другими словами, мы ничего не сравниваем вообще, а просто проводим фильтрацию коллекций, в итоге получая ArrrayList со всеми дублями.

**Comment by TwerTrue** [comment]
Я хочу узнать как мы получаем файл который уже был в карте ?
А так можно попробовать, хорошо что ты доробатываешь алгоритм

**Comment by GamBitGit** [comment]
Опишу свой метод поиска и сравнения файлов.

Изначально сделал так же как у Иван, но  процесс, получения списка всех файлов и нахождения одинаковых по размеру, сильно затягивался при проверке большой кучи мелких файлов, типа фоток, текстовых доков и т.д. Пример 3,45 гига, 1146 файлов, сканировались 5-6 секунд и это без проверки хешсуммы. Найденные файлы хранил в ArrayList<File>. Я предполагаю процесс затягивался из-за того, что объект класса File хранит много ненужной информации, а специфика эрэй листа пересоздавать массив при добавлении и удалении элементов это усугубляло. К слову замена ArrayList на LinkedList не особо помогала, значит дело в формате объекта. Пришлось написать небольшой класс ShortFile, из которых теперь состоял список и в который перед добавлением помещалась информация о имени, абсолютном пути и размере файла. Время проверки сократилось до 60-100мс.

Список дубликатов я закинул в HashMap<Long, Duplicate>, где ключ Long это размер файла, а Duplicate класс, написанный для хранения дубликатов. Он содержит имя и путь к первому файлу из списка дублей, а также массив с адресами его копий, включая его самого. Таким образов мы знаем какие дубликаты к какому файлу конкретно принадлежат и в дальнейшем будет удобно расширять класс, например, добавляя информацию о формате файла или дате создания.

Сейчас при добавлении сравнения по МД5 проверка больших файлов происходит неприемлемо долго. Попробую алгоритм Адлер, описанный НерВом.

Кстати, если кто разобрался как проверять файл кусками, а не целиком, отпишитесь, интересно

**Comment by seanjke** [comment]
Отличное предложение, с большой вероятностью, будем использовать ваш метод.

**Comment by Mauladen** [comment]
Пробуйте использовать некриптографические хеш-функции (В плане скорости они выигрывают)

**Comment by GamBitGit** [comment]
Адлер-32 работает быстрее чем МД5, но недостаточно, нужны другие варианты

**Comment by Mauladen** [comment]
Пробуй Ly, Rs, Rot13, FAQ6

**Comment by ilgaros** [comment]
Предлагаю внести кое-какие изменения в метод прохождения по дереву каталогов и сбора путей до файлов в них. 
Мы все данные о файлах в каталогах получаем через методы класса File. так же мы создаем каждый раз новый экземпляр этого класса для каждого файла, что, возможно, есть не самый лучший вариант. В Java имеется система NIO, там есть специальные средства для обхода дерева каталогов. Возможно, нам это пригодится. И тогда ArrayList можно заполнить просто стрингами - путями до каждого файла вместо объектов класса File. Насколько это быстрее работает я не проверял, но надо полагать, что новые средства работают лучше.

**Comment by GamBitGit** [comment]
Если мы получим список с адресами файлов, то чтобы вынуть дополнительную информацию, типа размера и имени все равно прийдется создавать объект класса файл по этому адресу. А вообще создание списка не занимает много времени, все занимает расчет и сравнение хеш-сумм

**Comment by ilgaros** [comment]
Если нам  когда-нибудь понадобится доступ к атрибутам файла, то все это есть в NIO: и классы атрибутов, и методы обработки и т.д. К тому же затраты по времени на создание экземпляров File, возможно, сейчас не так актуальны, когда файлов относительно немного. Нужны атрибуты - создавайте соответствующие объекты, не нужны - значит и плодить миллионы File просто так смысла нет. Везде говорится, что новый код должен использовать новые возможности.
Вообще я натыкался на сайтах на возмущения людей по поводу медлительности нашего метода обхода файлов (код как у нас один в один). Я лично замеры не проводил, поверил на слово. Так вот решение предлагали искать именно в NIO. Когда писали код нашего способа, в NIO таких возможностей еще не было.

**Comment by Mauladen** [comment]
Если код будет реально как черепаха то будем смотреть в твою сторону, сейчас просто принимать такие решения без смысленно

**Comment by chermenin** [comment]
Ребята, вопрос - зачем вообще проверять большие файлы? Сколько у вас на диске реально больших файлов (хотя бы более 100 Мб)? Нужно проверять всяческую мелочь, коей бывает много (документы, фотографии, музыку), а большие файлы можно просто выводить в список и то, только если  у них размеры совпадают. А уже если пользователь отдельно решит-таки удостовериться - тогда и будем считать хэши.
