### ISSUE TITLE
Варианты Logo для проекта

### ISSUE THREAD

**Issue by gressus** [khasang/JClean#6]

**Comment by gressus** [comment]
![jclean1_300x300](https://cloud.githubusercontent.com/assets/8287232/9290670/11670798-43a4-11e5-8810-a24bfd8bdcfe.png)
вариант 1

**Comment by gressus** [comment]
![jclean1_2_300x302](https://cloud.githubusercontent.com/assets/8287232/9290749/053b9404-43a7-11e5-84d8-7c12cfb2e35c.png)
вариант 2

**Comment by DemonStars** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/12501299/9292621/ed6a4808-441d-11e5-842d-71cfd6552850.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/12501299/9292622/f526c652-441d-11e5-8279-f15e7b45e5a4.jpg)
