### ISSUE TITLE
Решить проблему подсчета хэшсумм для больших файлов, с минимальными затратами по времени.

### ISSUE THREAD

**Issue by seanjke** [khasang/JClean#7]

**Comment by TwerTrue** [comment]
Мы будем проверять 15% или же можно и 9% (проверяем 3 части файла (начало файла, середина, конец файла))

**Comment by Mauladen** [comment]
Использовать многопоточность при сканировании

**Comment by GeorgeSemenov** [comment]
Помимо разбиения файлов по размером , как уже было сказано , предлагаю использовать не криптографическую хэш функцию MD5 , а какую-нибудь некриптографическую , разумеется вероятность коллизий будет выше , но при подозрении на коллизии можно брать первые килобайты данных и пропускать их через MD5 и сравнивать.Небольшая статья про простые хэш функции и их сравнение http://m.habrahabr.ru/post/219139/

**Comment by Mauladen** [comment]
Хороший вариант, там даже уже выделенные самые лучшее которые можно использовать
