### ISSUE TITLE
Разработка и обсуждение вариантов мокапов.

### ISSUE THREAD

**Issue by seanjke** [khasang/JClean#8]
Согласованный драфт дизайна:
![2015-08-23 21 34 20](https://cloud.githubusercontent.com/assets/8287232/9429832/84c983a8-49e6-11e5-9063-7368e514ad43.png)
![2015-08-23 21 19 45](https://cloud.githubusercontent.com/assets/8287232/9429834/8da4dbe4-49e6-11e5-9ccf-47cf85db74ae.png)
![2015-08-22 22 01 28](https://cloud.githubusercontent.com/assets/8287232/9429835/9237232e-49e6-11e5-8f72-adcbc22a7cf0.png)

**Comment by ilgaros** [comment]
https://moqups.com/mamedaliev.ilgar@gmail.com/OS5xGKld

**Comment by ilgaros** [comment]
https://moqups.com/mamedaliev.ilgar@gmail.com/OS5xGKld

**Comment by gressus** [comment]
![2015-08-22 22 32 29](https://cloud.githubusercontent.com/assets/8287232/9429538/23101cd0-49dc-11e5-9718-5b11a3cf2863.png)

**Comment by gressus** [comment]
![2015-08-22 22 01 28](https://cloud.githubusercontent.com/assets/8287232/9429539/3044b71c-49dc-11e5-9e78-44374cd135c6.png)

**Comment by gressus** [comment]
![2015-08-23 21 19 45](https://cloud.githubusercontent.com/assets/8287232/9429551/b37056fa-49dc-11e5-835d-32133cb11cb9.png)
1 и 2 страницы

**Comment by gressus** [comment]
Если пользователь не выбрал файл на 1 окне -- указано, что сканировать весь компьютер.
На 3-м окне -- добавить крестик -- чтобы закрыть карточку

**Comment by gressus** [comment]
![2015-08-23 21 34 20](https://cloud.githubusercontent.com/assets/8287232/9429603/c0923fa4-49de-11e5-8d10-6da41fa9dff1.png)
первая страница

**Comment by Mauladen** [comment]
Финальная версия мокапа для первой версии уже полностью готова
